//! TLS identities and mutual authentication by pinned certificate (design §7.1).
//!
//! Every replica has a self-signed certificate, generated by `init` and kept
//! next to its index (`<pair_dir>/<replica>.crt` and `.key`, never inside a
//! replica root). Its [`DeviceId`] is the blake3 hash of the certificate,
//! as in syncthing, and the pair config pins each replica's device ID.
//!
//! A connection to a replica's server is made on behalf of its peer: the
//! client presents the peer replica's certificate, and each side accepts
//! exactly the device ID pinned for the other one. No certificate authority,
//! name or validity period is involved; the TLS 1.3 handshake signature
//! proves that the other side holds the pinned certificate's key.

use std::fmt;
use std::path::{Path, PathBuf};
use std::str::FromStr;
use std::sync::Arc;

use rustls::client::danger::{HandshakeSignatureValid, ServerCertVerified, ServerCertVerifier};
use rustls::crypto::{CryptoProvider, WebPkiSupportedAlgorithms};
use rustls::pki_types::{CertificateDer, PrivateKeyDer, PrivatePkcs8KeyDer, ServerName, UnixTime};
use rustls::server::danger::{ClientCertVerified, ClientCertVerifier};
use rustls::{DigitallySignedStruct, DistinguishedName, SignatureScheme};
use serde::{Deserialize, Deserializer, Serialize, Serializer};

use crate::config::{ReplicaId, write_atomic};
use crate::error::{Error, Result};

/// The name the client asks for. Certificates are pinned, so it is not
/// checked; every certificate carries it anyway.
pub const SERVER_NAME: &str = "files-sync";

/// Identifies a replica's certificate: the blake3 hash of its DER encoding.
/// Written as 64 hex digits.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct DeviceId(pub [u8; 32]);

impl DeviceId {
    /// The device ID of the DER-encoded certificate `cert`.
    pub fn of(cert: &[u8]) -> DeviceId {
        DeviceId(*blake3::hash(cert).as_bytes())
    }
}

impl fmt::Display for DeviceId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for b in self.0 {
            write!(f, "{b:02x}")?;
        }
        Ok(())
    }
}

impl fmt::Debug for DeviceId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "DeviceId({self})")
    }
}

impl FromStr for DeviceId {
    type Err = String;

    fn from_str(s: &str) -> Result<DeviceId, String> {
        let bytes = s.as_bytes();
        if bytes.len() != 64 {
            return Err(format!("device id {s:?} must be 64 hex digits"));
        }
        let mut id = [0u8; 32];
        for (i, pair) in bytes.chunks(2).enumerate() {
            let pair = std::str::from_utf8(pair).map_err(|e| e.to_string())?;
            id[i] = u8::from_str_radix(pair, 16).map_err(|e| format!("device id {s:?}: {e}"))?;
        }
        Ok(DeviceId(id))
    }
}

impl Serialize for DeviceId {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.collect_str(self)
    }
}

impl<'de> Deserialize<'de> for DeviceId {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<DeviceId, D::Error> {
        String::deserialize(d)?
            .parse()
            .map_err(serde::de::Error::custom)
    }
}

fn tls_error(reason: impl fmt::Display) -> Error {
    Error::Tls {
        reason: reason.to_string(),
    }
}

/// A replica's certificate and private key.
pub struct Identity {
    cert: CertificateDer<'static>,
    key: PrivatePkcs8KeyDer<'static>,
}

impl fmt::Debug for Identity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Identity")
            .field("device", &self.device())
            .finish_non_exhaustive()
    }
}

impl Identity {
    /// A fresh self-signed certificate (ECDSA P-256) for `replica`.
    pub fn generate(replica: ReplicaId) -> Result<Identity> {
        let key = rcgen::KeyPair::generate().map_err(tls_error)?;
        let mut params =
            rcgen::CertificateParams::new(vec![SERVER_NAME.to_owned()]).map_err(tls_error)?;
        params.distinguished_name = rcgen::DistinguishedName::new();
        params.distinguished_name.push(
            rcgen::DnType::CommonName,
            format!("files_sync replica {replica}"),
        );
        let cert = params.self_signed(&key).map_err(tls_error)?;
        Ok(Identity {
            cert: cert.der().clone(),
            key: PrivatePkcs8KeyDer::from(key.serialize_der()),
        })
    }

    /// The certificate's device ID.
    pub fn device(&self) -> DeviceId {
        DeviceId::of(&self.cert)
    }

    /// The DER-encoded certificate.
    pub fn cert_der(&self) -> &[u8] {
        &self.cert
    }

    /// `<pair_dir>/<replica>.crt` and `<pair_dir>/<replica>.key`.
    pub fn paths(pair_dir: &Path, replica: ReplicaId) -> (PathBuf, PathBuf) {
        (
            pair_dir.join(format!("{replica}.crt")),
            pair_dir.join(format!("{replica}.key")),
        )
    }

    /// Writes the certificate and the key (mode 0600) for `replica` into
    /// `pair_dir`. Never replaces existing files.
    pub fn save(&self, pair_dir: &Path, replica: ReplicaId) -> Result<()> {
        let (cert, key) = Identity::paths(pair_dir, replica);
        write_atomic(&key, self.key.secret_pkcs8_der(), false)?;
        write_atomic(&cert, &self.cert, false)
    }

    /// Reads `replica`'s identity from `pair_dir`. Its device ID must be
    /// `expect` (the one the config pins).
    pub fn load(pair_dir: &Path, replica: ReplicaId, expect: DeviceId) -> Result<Identity> {
        let (cert_path, key_path) = Identity::paths(pair_dir, replica);
        let read = |path: &Path| {
            std::fs::read(path).map_err(|e| Error::io(format!("read {}", path.display()), e))
        };
        let identity = Identity {
            cert: CertificateDer::from(read(&cert_path)?),
            key: PrivatePkcs8KeyDer::from(read(&key_path)?),
        };
        if identity.device() != expect {
            return Err(tls_error(format!(
                "{} has device id {}, but the config pins {expect}",
                cert_path.display(),
                identity.device()
            )));
        }
        Ok(identity)
    }

    fn key(&self) -> PrivateKeyDer<'static> {
        PrivateKeyDer::Pkcs8(self.key.clone_key())
    }

    /// A server config that presents this identity and accepts only clients
    /// with device ID `peer`.
    pub fn server_config(&self, peer: DeviceId) -> Result<Arc<rustls::ServerConfig>> {
        let provider = provider();
        let verifier = Arc::new(Pinned::new(peer, &provider));
        let config = rustls::ServerConfig::builder_with_provider(provider)
            .with_protocol_versions(&[&rustls::version::TLS13])
            .map_err(tls_error)?
            .with_client_cert_verifier(verifier)
            .with_single_cert(vec![self.cert.clone()], self.key())
            .map_err(tls_error)?;
        Ok(Arc::new(config))
    }

    /// A client config that presents this identity and accepts only a
    /// server with device ID `peer`.
    pub fn client_config(&self, peer: DeviceId) -> Result<Arc<rustls::ClientConfig>> {
        let provider = provider();
        let verifier = Arc::new(Pinned::new(peer, &provider));
        let config = rustls::ClientConfig::builder_with_provider(provider)
            .with_protocol_versions(&[&rustls::version::TLS13])
            .map_err(tls_error)?
            .dangerous()
            .with_custom_certificate_verifier(verifier)
            .with_client_auth_cert(vec![self.cert.clone()], self.key())
            .map_err(tls_error)?;
        Ok(Arc::new(config))
    }
}

/// The server name a client connects with ([`SERVER_NAME`]).
pub fn server_name() -> ServerName<'static> {
    ServerName::try_from(SERVER_NAME).expect("a valid DNS name")
}

fn provider() -> Arc<CryptoProvider> {
    Arc::new(rustls::crypto::ring::default_provider())
}

/// Accepts exactly one certificate, by device ID; checks handshake
/// signatures with the provider's algorithms.
#[derive(Debug)]
struct Pinned {
    device: DeviceId,
    algorithms: WebPkiSupportedAlgorithms,
}

impl Pinned {
    fn new(device: DeviceId, provider: &CryptoProvider) -> Pinned {
        Pinned {
            device,
            algorithms: provider.signature_verification_algorithms,
        }
    }

    fn check(&self, cert: &CertificateDer<'_>) -> Result<(), rustls::Error> {
        let got = DeviceId::of(cert);
        if got == self.device {
            return Ok(());
        }
        let msg = format!("device id {got} is not the pinned {}", self.device);
        Err(rustls::Error::InvalidCertificate(
            rustls::CertificateError::Other(rustls::OtherError(Arc::new(std::io::Error::other(
                msg,
            )))),
        ))
    }
}

impl ServerCertVerifier for Pinned {
    fn verify_server_cert(
        &self,
        end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _server_name: &ServerName<'_>,
        _ocsp_response: &[u8],
        _now: UnixTime,
    ) -> Result<ServerCertVerified, rustls::Error> {
        self.check(end_entity)?;
        Ok(ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls12_signature(message, cert, dss, &self.algorithms)
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls13_signature(message, cert, dss, &self.algorithms)
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        self.algorithms.supported_schemes()
    }
}

impl ClientCertVerifier for Pinned {
    fn root_hint_subjects(&self) -> &[DistinguishedName] {
        &[]
    }

    fn verify_client_cert(
        &self,
        end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _now: UnixTime,
    ) -> Result<ClientCertVerified, rustls::Error> {
        self.check(end_entity)?;
        Ok(ClientCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls12_signature(message, cert, dss, &self.algorithms)
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls13_signature(message, cert, dss, &self.algorithms)
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        self.algorithms.supported_schemes()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn device_id_text_round_trip() {
        let id = DeviceId::of(b"cert");
        let s = id.to_string();
        assert_eq!(s.len(), 64);
        assert_eq!(s.parse::<DeviceId>().unwrap(), id);
        assert!("abc".parse::<DeviceId>().is_err());
        assert!("g".repeat(64).parse::<DeviceId>().is_err());
        assert!("é".repeat(32).parse::<DeviceId>().is_err());
    }

    #[test]
    fn identity_save_load_and_pin() {
        let dir = tempfile::tempdir().unwrap();
        let r = ReplicaId(7);
        let id = Identity::generate(r).unwrap();
        id.save(dir.path(), r).unwrap();
        // Never replaced.
        assert!(Identity::generate(r).unwrap().save(dir.path(), r).is_err());
        let back = Identity::load(dir.path(), r, id.device()).unwrap();
        assert_eq!(back.device(), id.device());
        let (_, key) = Identity::paths(dir.path(), r);
        use std::os::unix::fs::PermissionsExt;
        let mode = std::fs::metadata(key).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o600);
        let other = Identity::generate(r).unwrap();
        assert_ne!(other.device(), id.device());
        let err = Identity::load(dir.path(), r, other.device()).unwrap_err();
        assert!(err.to_string().contains("pins"), "{err}");
        // Both configs build.
        id.server_config(other.device()).unwrap();
        id.client_config(other.device()).unwrap();
    }
}
